#!/usr/bin/env python3
"""Add a small right-floated table of contents to Simplifier .page.md guides.

Runs over guides/**/*.page.md. For pages with more than 5 section headings
(## .. ######) it:
  - gives each section heading an <a name="slug"></a> anchor (existing anchors
    are reused, not duplicated),
  - inserts a boxed TOC that links to those anchors, floated on the right.

Idempotent: the TOC lives between AUTO-TOC markers and is regenerated each run;
headings that already carry an anchor are left as-is.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
GUIDES = ROOT / "guides"
MIN_HEADINGS = 5  # add TOC only when there are MORE than this many section headings
MAX_DEPTH = 2     # levels shown in the TOC (## and ### only); deeper headings still get anchors

START = "<!-- AUTO-TOC:START -->"
END = "<!-- AUTO-TOC:END -->"
HEADING = re.compile(r"^(#{2,6})\s+(.*)$")
NAME_ANCHOR = re.compile(r'<a\s+name="([^"]+)"\s*>\s*</a>')  # legacy form, normalized on run
TRAILING_ID = re.compile(r'\s*\{#([A-Za-z0-9_-]+)\}\s*$')    # kramdown/pandoc form: ## Foo {#foo}


def strip_anchors(text):
    return TRAILING_ID.sub("", NAME_ANCHOR.sub("", text))


def slugify(text):
    text = strip_anchors(text)
    text = re.sub(r"\{\{[^}]*\}\}", "", text)      # drop {{pagelink:...}} etc.
    text = re.sub(r"<[^>]+>", "", text)            # drop remaining html
    text = re.sub(r"[`*_]", "", text)              # drop md emphasis marks
    slug = re.sub(r"[^A-Za-z0-9]+", "-", text.strip().lower()).strip("-")
    return slug or "section"


def clean_text(text):
    text = strip_anchors(text)
    text = re.sub(r"\{\{[^}]*?text:\s*([^,}]+)[^}]*\}\}", r"\1", text)  # pagelink -> its text
    text = re.sub(r"\{\{[^}]*\}\}", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"[`*_]", "", text)
    return text.strip()


def parse(lines):
    """Yield (index, level, anchor, display_text) for each section heading
    outside code fences. Mutates nothing."""
    in_fence = False
    seen = set()
    for i, line in enumerate(lines):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING.match(line)
        if not m:
            continue
        level = len(m.group(1))
        body = m.group(2)
        found = TRAILING_ID.search(body) or NAME_ANCHOR.search(body)
        anchor = found.group(1) if found else slugify(body)
        base, n = anchor, 2
        while anchor in seen:  # guarantee uniqueness
            anchor, n = f"{base}-{n}", n + 1
        seen.add(anchor)
        yield i, level, anchor, clean_text(body)


def build_toc(headings):
    top = min(h[1] for h in headings)
    shown = [h for h in headings if h[1] < top + MAX_DEPTH]
    items = []
    for _, level, anchor, text in shown:
        # the one sub-level is indented; styling lives in the IG's style.css
        cls = "" if level == top else ' class="toc-sub"'
        items.append(f'<li{cls}><a href="#{anchor}">{text}</a></li>')
    return "\n".join([
        START,
        "<!-- Do NOT edit this block by hand: it is generated by scripts/add_page_toc.py.",
        "     Change the headings and re-run `python scripts/add_page_toc.py` instead.",
        "     itoc = the template's right-floated yellow box; .page-toc widens it and",
        "     styles the link list (see styles/next-level-custom-styling/style.css). -->",
        '<div class="itoc page-toc">',
        '<ul>',
        *[f"  {it}" for it in items],
        '</ul>',
        '</div>',
        END,
    ])


def process(path):
    text = path.read_text(encoding="utf-8")
    # strip any previous TOC block (and the blank lines around it) so the run is idempotent
    text = re.sub(r"\n*" + re.escape(START) + r".*?" + re.escape(END) + r"\n*", "\n", text, flags=re.S)
    lines = text.split("\n")

    headings = list(parse(lines))
    if len(headings) <= MIN_HEADINGS:
        return False

    # normalize every heading to `## Text {#anchor}` (idempotent, converts legacy <a name>)
    for i, level, anchor, _ in reversed(headings):
        marker, body = HEADING.match(lines[i]).groups()
        body = strip_anchors(body).rstrip()
        lines[i] = f'{marker} {body} {{#{anchor}}}'

    # insert the TOC after frontmatter and the first H1 (fall back to top)
    insert_at = 0
    if lines and lines[0].strip() == "---":
        end_fm = next((j for j in range(1, len(lines)) if lines[j].strip() == "---"), 0)
        insert_at = end_fm + 1
    h1 = next((j for j in range(insert_at, len(lines)) if lines[j].startswith("# ")), None)
    if h1 is not None:
        insert_at = h1 + 1

    toc = build_toc(headings)
    lines[insert_at:insert_at] = ["", toc, ""]
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return True


def main():
    changed = 0
    for path in sorted(GUIDES.rglob("*.page.md")):
        if process(path):
            changed += 1
            print(f"TOC added: {path.relative_to(ROOT)}")
    print(f"{changed} page(s) updated.")


if __name__ == "__main__":
    sys.exit(main())
