#!/usr/bin/env python3
"""Generate the Artifact Index page (technical_artifacts/artifacts/index.page.md).

Mimics the tables on https://build.fhir.org/ig/HL7/us-behavioral-health-profiles/artifacts.html:

  Profiles    - one row per StructureDefinition in fsh-generated (title, description)
  Terminology - one row per ValueSet / CodeSystem in fsh-generated (title, description)
  Examples    - one row per examples/*.page.md, description taken from its frontmatter

Rewrites the file on every run; run it after SUSHI.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
RESOURCES = ROOT / "fsh-generated" / "resources"
ARTIFACTS = ROOT / "guides/us-behavioral-health-profiles/ig/technical_artifacts/artifacts"
OUT = ARTIFACTS / "index.page.md"

INTRO = "This page provides a list of the FHIR artifacts defined as part of this implementation guide."

# ponytail: frontmatter here is always `key: value` one-liners, so no PyYAML dependency
FM_KEY = re.compile(r"^([A-Za-z_][\w-]*)\s*:\s*(.*?)\s*$")


def frontmatter(path):
    lines = path.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    out = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = FM_KEY.match(line)
        if m:
            out[m.group(1)] = m.group(2).strip().strip("\"'")
    return out


def resources(*types):
    for path in sorted(RESOURCES.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("resourceType") in types:
            yield data


def cell(text):
    return html.escape(text or "", quote=False)


def table(rows):
    """Header-less grid table; table.grid styling already ships in the IG stylesheet."""
    body = ""
    for row in rows:
        cells = "".join(f"     <td>{c}</td>\n" for c in row)
        body += f"  <tr>\n{cells}  </tr>\n"
    return f'<table class="grid" style="width:100%">\n<tbody>\n{body}</tbody>\n</table>'


def profiles():
    rows = []
    for sd in resources("StructureDefinition"):
        if sd.get("kind") == "logical":
            continue
        title = sd.get("title") or sd.get("name") or sd["id"]
        link = f"{{{{pagelink:StructureDefinition-{sd['id']}, text:{title}}}}}"
        rows.append((title, [link, cell(sd.get("description"))]))
    return table([r for _, r in sorted(rows)])


def terminology():
    rows = []
    for res in resources("ValueSet", "CodeSystem"):
        kind = res["resourceType"]
        title = res.get("title") or res.get("name") or res["id"]
        link = f"{{{{pagelink:{kind}-{res['id']}, text:{title}}}}}"
        rows.append((title, [link, cell(res.get("description"))]))
    return table([r for _, r in sorted(rows)])


def examples():
    rows = []
    for path in sorted((ARTIFACTS / "examples").glob("*.page.md")):
        fm = frontmatter(path)
        topic = fm.get("topic", "")
        if not topic.startswith("example-"):
            continue  # index.page.md and anything else that is not an example page
        rtype = fm.get("subject", "/").split("/")[0]
        rows.append((rtype, topic, [f"{{{{pagelink:{topic}}}}}", cell(fm.get("description"))]))
    return table([r for _, _, r in sorted(rows)])


def main():
    page = "\n".join([
        "---",
        "topic: artifacts",
        "---",
        "",
        "<!-- Do NOT edit this page by hand: it is generated by scripts/build_artifacts_index.py",
        "     from fsh-generated/resources and the frontmatter of the example pages. -->",
        "",
        "# {{page-title}}",
        "",
        INTRO,
        "",
        "## Profiles",
        "",
        profiles(),
        "",
        "## Terminology",
        "",
        terminology(),
        "",
        "## Examples",
        "",
        examples(),
        "",
    ])
    OUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


def demo():
    """Self-check: frontmatter parsing + table rendering."""
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "x.page.md"
        p.write_text('---\ntopic: example-a\nsubject: Patient/a\ndescription: "Hi: there"\n---\n\n## body\n', encoding="utf-8")
        fm = frontmatter(p)
        assert fm == {"topic": "example-a", "subject": "Patient/a", "description": "Hi: there"}, fm
    t = table([[cell("<x> & y")]])
    assert "&lt;x&gt; &amp; y" in t and t.count("<tr>") == 1, t
    print("ok")


if __name__ == "__main__":
    sys.exit(demo() if "--demo" in sys.argv else main())
