#!/usr/bin/env python3
"""Generate the IP Statements block on the downloads page.

Mirrors the FHIR IG publisher's IPStatementsRenderer:
 - collect every code system URI used by the IG's resources
 - find a copyright statement for each (hard-coded for the big ones, else CodeSystem.copyright)
 - group the systems by statement and list what uses them

Rewrites the block between the BEGIN/END markers in downloads.page.md on every run.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
RESOURCES = ROOT / "fsh-generated" / "resources"
ARTIFACTS = ROOT / "guides/us-behavioral-health-profiles/ig/technical_artifacts/artifacts"
PAGE = ROOT / "guides/us-behavioral-health-profiles/ig/downloads.page.md"
CACHE = Path.home() / ".fhir" / "packages"
SUSHI = ROOT / "sushi-config.yaml"

BEGIN = "<!-- BEGIN ip-statements (generated by scripts/build_ip_statements.py) -->"
END = "<!-- END ip-statements -->"
INTRO = "This publication includes IP covered under the following statements."
NONE = "No use of external IP (other than from the FHIR specification)"
# The publisher's button, minus its JS: list-style:none drops the <details> triangle.
SUMMARY = ('<summary style="list-style: none; display: inline-block">'
           '<span style="cursor: pointer; border: 1px grey solid; background-color: #fcdcb3; '
           'padding-left: 3px; padding-right: 3px; color: black">Show Usage</span></summary>')

# Statements the publisher hard-codes; SNOMED/LOINC also override the display name.
SNOMED = "http://snomed.info/sct"
LOINC = "http://loinc.org"
FIXED = {
    SNOMED: ("SNOMED Clinical Terms® (SNOMED CT®)",
             "This material contains content that is copyright of SNOMED International. Implementers of these "
             "specifications must have the appropriate SNOMED CT Affiliate license - for more information contact "
             '<a href="https://www.snomed.org/get-snomed">https://www.snomed.org/get-snomed</a> or '
             '<a href="mailto:info@snomed.org">info@snomed.org</a>.'),
    LOINC: ("LOINC",
            'This material contains content from <a href="http://loinc.org">LOINC</a>. LOINC is copyright &copy; '
            "1995-2020, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) "
            'Committee and is available at no cost under the <a href="http://loinc.org/license">license</a>. '
            "LOINC&reg; is a registered United States trademark of Regenstrief Institute, Inc."),
    "http://nucc.org/provider-taxonomy": (None,
            "National Uniform Claim Committee (NUCC) Copyright 2026 American Medical Association. The National "
            "Uniform Claim Committee (NUCC) maintains the Health Insurance Claim Form (1500 Claim Form), the 1500 "
            "Health Insurance Claim Form Reference Instruction Manual (NUCC 1500 Instruction Manual) and two NUCC "
            "Data Sets, the Health Care Provider Taxonomy Code Set and the Provider Characteristics and Resources "
            "code set. As the NUCC Secretariat, the AMA holds the intellectual property on behalf of the NUCC and "
            "maintains the copyright of materials developed by the NUCC. For commercial use, including sales and "
            "redistribution, a license must be obtained."),
}
# Checked only when the CodeSystem itself carries no copyright.
FALLBACK = {
    "http://www.ama-assn.org/go/cpt":
        "Current Procedural Terminology (CPT) is copyright 2020 American Medical Association. All rights reserved",
    "http://www.whocc.no/atc":
        "This artifact includes content from Anatomical Therapeutic Chemical (ATC) classification system. ATC codes "
        "are copyright World Health Organization (WHO) Collaborating Centre for Drug Statistics Methodology. Terms & "
        "Conditions in https://www.whocc.no/use_of_atc_ddd/",
    "urn:oid:2.16.840.1.113883.2.9.6.2.7":
        "This artifact includes content from International Standard Classification of Occupations (ISCO). ISCO is "
        "copyright International Labour Organization (ILO). Terms & Conditions in "
        "http://www.ilo.org/global/copyright/lang--en/index.htm",
    "http://standardterms.edqm.eu":
        "This artifact includes content from EDQM Standard Terms. EDQM Standard Terms are copyright European "
        "Directorate for the Quality of Medicines. Terms & Conditions in "
        "https://www.edqm.eu/en/standard-terms-database",
}
THO = ("This material derives from the HL7 Terminology (THO). THO is copyright ©1989+ Health Level Seven "
       "International and is made available under the CC0 designation. For more licensing information see: "
       "https://terminology.hl7.org/license.html")

FM_KEY = re.compile(r"^([A-Za-z_][\w-]*)\s*:\s*(.*?)\s*$")
MD_LINK = re.compile(r"\[([^\]]+)\]\((\S+?)\)")
BARE_URL = re.compile(r"(?<![\"(>])\bhttps?://[^\s<>\)\]]+[^\s<>\)\],.]")


def frontmatter(path):
    lines = path.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    out = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = FM_KEY.match(line)
        if m:
            out[m.group(1)] = m.group(2).strip().strip("\"'")
    return out


def markdown_to_html(text):
    """ponytail: copyright fields only ever use links + bare URLs, so no markdown dependency."""
    out = html.escape(text, quote=False)
    out = MD_LINK.sub(lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>', out)
    out = BARE_URL.sub(lambda m: f'<a href="{m.group(0)}">{m.group(0)}</a>', out)
    return " ".join(out.split())


# ---------------------------------------------------------------- code systems

def dependencies():
    """Direct dependencies from sushi-config.yaml (the `dependencies:` block of id: version lines)."""
    deps, inside = {}, False
    for line in SUSHI.read_text(encoding="utf-8").split("\n"):
        if line.startswith("dependencies:"):
            inside = True
            continue
        if inside:
            if line[:1] not in (" ", "\t"):
                break
            m = re.match(r"\s+([\w.\-]+)\s*:\s*([^\s#]+)", line)
            if m:
                deps[m.group(1)] = m.group(2).strip("\"'")
    return deps


def version_key(ver):
    return tuple(int(p) if p.isdigit() else -1 for p in re.split(r"[.\-+]", ver))


def packages():
    """Cached package dirs: the dependency closure first, the FHIR core spec last.

    That is the publisher's precedence - a dependency (notably HL7 Terminology, which is
    where the THO copyright statements live) overrides the core spec's copy of a code
    system. Where the closure asks for a package twice, the highest version wins.
    """
    order, best, todo, seen = [], {}, list(dependencies().items()) + [("hl7.fhir.r4.core", "4.0.1")], set()
    while todo:
        pid, ver = todo.pop(0)
        if (pid, ver) in seen:
            continue
        seen.add((pid, ver))
        pkg = CACHE / f"{pid}#{ver}" / "package"
        if not pkg.is_dir():
            print(f"  note: {pid}#{ver} not in the package cache - its copyrights are skipped", file=sys.stderr)
            continue
        if pid not in best:
            order.append(pid)
        if pid not in best or version_key(ver) > version_key(best[pid]):
            best[pid] = ver
        meta = pkg / "package.json"
        if meta.exists():
            todo += list(json.loads(meta.read_text(encoding="utf-8")).get("dependencies", {}).items())
    dirs = [CACHE / f"{pid}#{best[pid]}" / "package" for pid in order]
    return sorted(dirs, key=lambda p: p.parent.name.startswith("hl7.fhir.r4.core"))  # stable: core last


def code_systems(wanted):
    """url -> CodeSystem, from fsh-generated plus the cached dependencies.

    Only the wanted urls are read; .index.json tells us which file holds which url.
    """
    out = {}
    for pkg in packages():
        index = pkg / ".index.json"
        if not index.exists():
            continue
        for entry in json.loads(index.read_text(encoding="utf-8")).get("files", []):
            url = entry.get("url")
            if entry.get("resourceType") == "CodeSystem" and url in wanted and url not in out:
                out[url] = json.loads((pkg / entry["filename"]).read_text(encoding="utf-8"))
    for path in RESOURCES.glob("CodeSystem-*.json"):  # our own definitions win
        cs = json.loads(path.read_text(encoding="utf-8"))
        out[cs.get("url")] = cs
    return out


def statement_for(system, cs):
    """(display name, copyright HTML) or (name, None) when the system carries no IP."""
    if system in FIXED:
        desc, stmt = FIXED[system]
        return desc or (cs and (cs.get("title") or cs.get("name"))) or system, stmt
    desc = (cs.get("title") or cs.get("name") or system) if cs else system
    if cs and cs.get("copyright"):
        text = cs["copyright"]
        if "HL7 Terminology" in text:
            text = THO
        return desc, markdown_to_html(text)
    if system in FALLBACK:
        return desc, markdown_to_html(FALLBACK[system])
    return desc, None


# ------------------------------------------------------------------ our resources

def walk(node, hit):
    """Collect Coding.system / Quantity.system (both carry `code`; Identifier.system does not)."""
    if isinstance(node, dict):
        if isinstance(node.get("system"), str) and "code" in node:
            hit(node["system"])
        for key in ("include", "exclude", "contains"):  # ValueSet compose / expansion
            for entry in node.get(key, []) or []:
                if isinstance(entry, dict) and isinstance(entry.get("system"), str):
                    hit(entry["system"])
        if node.get("resourceType") == "CodeSystem" and node.get("supplements"):
            hit(node["supplements"])
        for value in node.values():
            walk(value, hit)
    elif isinstance(node, list):
        for item in node:
            walk(item, hit)


def page_links():
    """'Type/id' and canonical url -> page topic, taken from the artifact pages' frontmatter."""
    links = {}
    for path in ARTIFACTS.glob("*.page.md"):
        fm = frontmatter(path)
        topic = fm.get("topic")
        if topic:
            for key in ("subject", "canonical"):
                if fm.get(key):
                    links[fm[key]] = topic
    return links


def usages():
    """system uri -> {resource label: page topic or None}"""
    links, found = page_links(), {}
    for path in sorted(RESOURCES.glob("*.json")):
        res = json.loads(path.read_text(encoding="utf-8"))
        ref = f"{res['resourceType']}/{res['id']}"
        label = res.get("title") or res.get("name") or ref
        topic = links.get(ref) or links.get(res.get("url"))
        if topic and topic.startswith("example-"):
            label = ref  # examples are listed by Type/id, the way the publisher does it
        walk(res, lambda s: found.setdefault(s, {}).update({label: topic}))
    return found


# ---------------------------------------------------------------------- render

def link(label, topic):
    return f"{{{{pagelink:{topic}, text:{label}}}}}" if topic else html.escape(label, quote=False)


def sentence(items):
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def render(found, systems):
    groups = {}
    for system, uses in found.items():
        desc, stmt = statement_for(system, systems.get(system))
        if stmt:
            groups.setdefault(stmt, []).append((desc, uses))
    if not groups:
        return NONE
    out = [f"<p>{INTRO}</p>", "<ul>"]
    for stmt in sorted(groups):
        out.append(f"  <li>{stmt}")
        # ponytail: <details> instead of the publisher's JS toggle - same behaviour, no script
        out.append(f"    <details>{SUMMARY}")
        out.append("    <ul>")
        for desc, uses in sorted(groups[stmt]):
            used = sentence([link(lbl, uses[lbl]) for lbl in sorted(uses)])
            out.append(f"      <li>{html.escape(desc, quote=False)}: {used}</li>")
        out.append("    </ul>")
        out.append("    </details>")
        out.append("  </li>")
    out.append("</ul>")
    return "\n".join(out)


def main():
    found = usages()
    block = f"{BEGIN}\n\n## IP Statements\n\n{render(found, code_systems(set(found)))}\n\n{END}"
    text = PAGE.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    PAGE.write_text(text, encoding="utf-8")
    print(f"wrote IP statements into {PAGE.relative_to(ROOT)}")


def demo():
    """Self-check: system collection, statement lookup, grouping and rendering."""
    hits = []
    walk({"resourceType": "Observation",
          "code": {"coding": [{"system": "http://loinc.org", "code": "1"}]},
          "identifier": [{"system": "http://example.org/ids", "value": "x"}],
          "valueQuantity": {"value": 1, "system": "http://unitsofmeasure.org", "code": "mg"}},
         hits.append)
    assert sorted(hits) == ["http://loinc.org", "http://unitsofmeasure.org"], hits
    hits = []
    walk({"resourceType": "ValueSet", "compose": {"include": [{"system": SNOMED}]}}, hits.append)
    assert hits == [SNOMED], hits

    assert statement_for(SNOMED, None)[0].startswith("SNOMED"), statement_for(SNOMED, None)
    assert statement_for("http://x", {"copyright": "from HL7 Terminology"})[1].startswith(
        "This material derives from the HL7 Terminology")
    assert statement_for("http://x", {"name": "X"}) == ("X", None)
    assert '<a href="http://a.b">here</a>' in markdown_to_html("see [here](http://a.b)")
    assert '<a href="http://a.b">http://a.b</a>' in markdown_to_html("see http://a.b.")

    out = render({LOINC: {"Observation/x": "example-x", "My Profile": None}}, {})
    assert "Show Usage" in out and "{{pagelink:example-x, text:Observation/x}}" in out and "My Profile" in out, out
    assert render({"http://example.org/free": {"a": None}}, {}) == NONE
    assert sentence(["a", "b", "c"]) == "a, b and c"
    print("ok")


if __name__ == "__main__":
    sys.exit(demo() if "--demo" in sys.argv else main())
