// =====================================================================
// USCDI+ BH Data Class: Health Status Assessments
// =====================================================================

Instance: phq-9-example-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "Patient Health Questionnaire-9 (PHQ-9)"
Description: "Example of a depression assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "http://hl7.org/fhir/us/core/Questionnaire/phq-9-example|6.1.0"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/44250-9"
* item[=].text = "Little interest or pleasure in doing things?"
* item[=].answer.valueCoding = $loinc#LA6570-1 "More than half the days"
* item[+].linkId = "/44255-8"
* item[=].text = "Feeling down, depressed, or hopeless?"
* item[=].answer.valueCoding = $loinc#LA6570-1 "More than half the days"
* item[+].linkId = "/44259-0"
* item[=].text = "Trouble falling or staying asleep, or sleeping too much"
* item[=].answer.valueCoding = $loinc#LA6570-1 "More than half the days"
* item[+].linkId = "/44254-1"
* item[=].text = "Feeling tired or having little energy"
* item[=].answer.valueCoding = $loinc#LA6570-1 "More than half the days"
* item[+].linkId = "/44251-7"
* item[=].text = "Poor appetite or overeating"
* item[=].answer.valueCoding = $loinc#LA6569-3 "Several days"
* item[+].linkId = "/44258-2"
* item[=].text = "Feeling bad about yourself-or that you are a failure or have let yourself or your family down"
* item[=].answer.valueCoding = $loinc#LA6569-3 "Several days"
* item[+].linkId = "/44252-5"
* item[=].text = "Trouble concentrating on things, such as reading the newspaper or watching television"
* item[=].answer.valueCoding = $loinc#LA6570-1 "More than half the days"
* item[+].linkId = "/44253-3"
* item[=].text = "Moving or speaking so slowly that other people could have noticed. Or the opposite-being so fidgety or restless that you have been moving around a lot more than usual"
* item[=].answer.valueCoding = $loinc#LA6568-5 "Not at all"
* item[+].linkId = "/44260-8"
* item[=].text = "Thoughts that you would be better off dead, or of hurting yourself in some way"
* item[=].answer.valueCoding = $loinc#LA6568-5 "Not at all"
* item[+].linkId = "/44261-6"
* item[=].text = "Patient health questionnaire 9 item total score"
* item[=].answer.valueDecimal = 12
* item[+].linkId = "/69722-7"
* item[=].text = "How difficult have these problems made it for you to do your work, take care of things at home, or get along with other people?"
* item[=].answer.valueCoding = $loinc#LA6573-5 "Somewhat difficult"

Instance: cognitive-status-observation-example-3
InstanceOf: Observation
Usage: #example
Title: "Mini-Mental State Examination [MMSE]"
Description: "Example of a mental/cognitive health status assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-screening-assessment|6.1.0"
* status = #final
* category[0] = $observation-category#survey "Survey"
* category[=].text = "Survey"
* category[+] = $us-core-category#cognitive-status "Cognitive Status"
* category[=].text = "Cognitive Status Category"
* code = $loinc#72107-6 "Mini-Mental State Examination [MMSE]"
* code.text = "Mini-Mental State Examination [MMSE]"
* subject = Reference(bh-patient-example) "James Wolff"
* effectiveDateTime = "2024-02-01"
* performer = Reference(mental-health-provider-example-1) "Dr. Lazslo Cravensworth"
* component.code = $loinc#72106-8 "Total score [MMSE]"
* component.code.text = "Total score [MMSE]"
* component.valueInteger = 30

Instance: anxiety-assessment-observation-example-1
InstanceOf: Observation
Usage: #example
Title: "anxiety-assessment-obs-example"
Description: "Example of patient anxiety assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-screening-assessment|6.1.0"
* status = #final
* category = $observation-category#survey "Survey"
* category.text = "Survey"
* code = $loinc#71891-6 "M3 Checklist - follow-up [M3]"
* code.text = "M3 Checklist"
* subject = Reference(bh-patient-example) "James Wolff"
* effectiveDateTime = "2024-02-01"
* performer = Reference(mental-health-provider-example-1) "Dr. Lazslo Cravensworth"
* component.code = $loinc#71816-3 "I have attacks of anxiety or panic since I took my last screen [M3]"
* component.code.text = "I have attacks of anxiety or panic since I took my last screen [M3]"
* component.valueCodeableConcept = $loinc#LA14734-0 "Most of the time"
* component.valueCodeableConcept.text = "Most of the time"

Instance: alcohol-use-identification-test-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "Alcohol Use Disorder Identification Test - Consumption [AUDIT-C]"
Description: "Example of patient alcohol abuse health status assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "http://hl7.org/fhir/us/core/Questionnaire/AUDIT-C"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/68517-2"
* item[=].text = "How many times in the past year have you have X or more drinks in a day?"
* item[=].answer.valueDecimal = 3
* item[+].linkId = "/68519-8"
* item[=].text = "How many standard drinks containing alcohol do you have on a typical day?"
* item[=].answer.valueCoding = $loinc#LA15695-2 "3 or 4"
* item[+].linkId = "/68520-6"
* item[=].text = "How often do you have 6 or more drinks on 1 occasion?"
* item[=].answer.valueCoding = $loinc#LA18876-5 "Monthly"
* item[+].linkId = "/75626-2"
* item[=].text = "Total score [AUDIT-C]"
* item[=].answer.valueDecimal = 3

Instance: disability-status-observation-example-1
InstanceOf: Observation
Usage: #example
Title: "Comprehensive Universal Behavior Health Screen (CUBS)©"
Description: "Example of disability status health status assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-screening-assessment|6.1.0"
* status = #final
* category = $observation-category#survey "Survey"
* category.text = "Survey"
* code = $loinc#89571-4 "Disability status [CUBS]"
* code.text = "Disability status [CUBS]"
* subject = Reference(bh-patient-example) "James Wolff"
* effectiveDateTime = "2024-02-01"
* performer = Reference(mental-health-provider-example-1) "Dr. Lazslo Cravensworth"
* valueCodeableConcept = $loinc#LA29243-5 "I'm Vulnerable - I sometimes or periodically have acute or chronic symptoms affecting housing, employment, social interactions, etc."
* valueCodeableConcept.text = "I'm Vulnerable - I sometimes or periodically have acute or chronic symptoms affecting housing, employment, social interactions, etc."

Instance: BHP-QuestionnaireResponsePRAPAREExample-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "prapare-questionnaireresponse-example"
Description: "Example of SDOH assessment/screening"
* meta.profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaireresponse"
* questionnaire = "http://hl7.org/fhir/us/sdoh-clinicalcare/Questionnaire/SDOHCC-QuestionnairePRAPARE#2.3.0"
* questionnaire.extension.url = "http://hl7.org/fhir/StructureDefinition/display"
* questionnaire.extension.valueString = "SDOHCC Questionnaire PRAPARE"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T13:56:33.747Z"
* item.linkId = "/93025-5"
* item.text = "Protocol for Responding to and Assessing Patients' Assets, Risks, and Experiences [PRAPARE]"
* item.item[0].linkId = "/93043-8"
* item.item[=].text = "Personal characteristics"
* item.item[=].item[0].linkId = "/93043-8/56051-6"
* item.item[=].item[=].text = "Hispanic or Latino"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93043-8/32624-9"
* item.item[=].item[=].text = "Race"
* item.item[=].item[=].answer.valueCoding = $loinc#LA14042-8 "Black/African American"
* item.item[=].item[+].linkId = "/93043-8/93035-4"
* item.item[=].item[=].text = "Has season or migrant farm work been your or your family's main source of income at any point in past 2 years?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93043-8/93034-7"
* item.item[=].item[=].text = "Have you been discharged from the armed forces of the United States?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93043-8/54899-0"
* item.item[=].item[=].text = "Preferred language"
* item.item[=].item[=].answer.valueCoding = $loinc#LA43-5 "English"
* item.item[+].linkId = "/93042-0"
* item.item[=].text = "Family and home"
* item.item[=].item[0].linkId = "/93042-0/63512-8"
* item.item[=].item[=].text = "How many people are living or staying at this address?"
* item.item[=].item[=].answer.valueInteger = 6
* item.item[=].item[+].linkId = "/93042-0/71802-3"
* item.item[=].item[=].text = "Housing status"
* item.item[=].item[=].answer.valueCoding = $loinc#LA30190-5 "I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)"
* item.item[=].item[+].linkId = "/93042-0/93033-9"
* item.item[=].item[=].text = "Are you worried about losing your housing?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA30122-8 "I choose not to answer this question"
* item.item[=].item[+].linkId = "/93042-0/56799-0"
* item.item[=].item[=].text = "Address"
* item.item[=].item[=].answer.valueString = "Broadway"
* item.item[+].linkId = "/93041-2"
* item.item[=].text = "Money and resources"
* item.item[=].item[0].linkId = "/93041-2/82589-3"
* item.item[=].item[=].text = "Highest level of educ"
* item.item[=].item[=].answer.valueCoding = $loinc#LA30191-3 "Less than high school degree"
* item.item[=].item[+].linkId = "/93041-2/67875-5"
* item.item[=].item[=].text = "Employment status current"
* item.item[=].item[=].answer.valueCoding = $loinc#LA17956-6 "Unemployed"
* item.item[=].item[+].linkId = "/93041-2/76437-3"
* item.item[=].item[=].text = "Primary insurance"
* item.item[=].item[=].answer.valueCoding = $loinc#LA17849-3 "Medicaid"
* item.item[=].item[+].linkId = "/93041-2/63586-2"
* item.item[=].item[=].text = "What was your best estimate of the total income of all family members from all sources, before taxes, in last year?"
* item.item[=].item[=].answer.valueDecimal = 25000
* item.item[=].item[+].linkId = "/93041-2/93031-3"
* item.item[=].item[=].text = "In the past year, have you or any family members you live with been unable to get any of the following when it was really needed?"
* item.item[=].item[=].answer[0].valueCoding = $loinc#LA30126-9 "Clothing"
* item.item[=].item[=].answer[+].valueCoding = $loinc#LA30127-7 "Child care"
* item.item[=].item[+].linkId = "/93041-2/93030-5"
* item.item[=].item[=].text = "Has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living?"
* item.item[=].item[=].answer[0].valueCoding = $loinc#LA30134-3 "Yes, it has kept me from non-medical meetings, appointments, work, or from getting things that I need"
* item.item[=].item[=].answer[+].valueCoding = $loinc#LA30133-5 "Yes, it has kept me from medical appointments or from getting my medications"
* item.item[+].linkId = "/93040-4"
* item.item[=].text = "Social and emotional health"
* item.item[=].item[0].linkId = "/93040-4/93029-7"
* item.item[=].item[=].text = "How often do you see or talk to people that you care about and feel close to (For example: talking to friends on the phone, visiting friends or family, going to church or club meetings)?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA30130-1 "1 or 2 times a week"
* item.item[=].item[+].linkId = "/93040-4/93038-8"
* item.item[=].item[=].text = "Stress is when someone feels tense, nervous, anxious or can't sleep at night because their mind is troubled. How stressed are you?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA13909-9 "Somewhat"
* item.item[+].linkId = "/93039-6"
* item.item[=].text = "Optional additional questions"
* item.item[=].item[0].linkId = "/93039-6/93028-9"
* item.item[=].item[=].text = "In the past year, have you spent more than 2 nights in a row in a jail, prison, detention center, or juvenile correctional facility?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93039-6/93027-1"
* item.item[=].item[=].text = "Are you a refugee?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93039-6/93026-3"
* item.item[=].item[=].text = "Do you feel physically and emotionally safe where you currently live?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item.item[=].item[+].linkId = "/93039-6/76501-6"
* item.item[=].item[=].text = "Within the last year, have you been afraid of your partner or ex-partner?"
* item.item[=].item[=].answer.valueCoding = $loinc#LA32-8 "No"

Instance: barthel-index-functional-status-example-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "barthel-index-example"
Description: "Example of patient barthel index functional status (panel)"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "https://www.sralab.org/sites/default/files/2017-07/barthel.pdf"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/83184-2"
* item[=].text = "Feeding or eating ability"
* item[=].answer.valueCoding = $loinc#LA12302-8 "Independent"
* item[+].linkId = "/83185-9"
* item[=].text = "Transferring ability"
* item[=].answer.valueCoding = $loinc#LA12302-8 "Independent"
* item[+].linkId = "/96767-9"
* item[=].text = "Grooming ability"
* item[=].answer.valueCoding = $loinc#LA31644-0 "Independent face/hair/teeth/shaving (implements provided)"
* item[+].linkId = "/83183-4"
* item[=].text = "Toileting ability"
* item[=].answer.valueCoding = $loinc#LA31632-5 "Independent (on and off, dressing, wiping)"
* item[+].linkId = "/83181-8"
* item[=].text = "Bathing ability"
* item[=].answer.valueCoding = $loinc#LA31636-6 "Independent (or in shower)"
* item[+].linkId = "/83186-7"
* item[=].text = "Ambulation ability"
* item[=].answer.valueCoding = $loinc#LA31642-4 "Independent (but may use any aid; for example, stick) >50 yards"
* item[+].linkId = "/96758-8"
* item[=].text = "Stairs ability"
* item[=].answer.valueCoding = $loinc#LA12302-8 "Independent"
* item[+].linkId = "/83182-6"
* item[=].text = "Dressing ability"
* item[=].answer.valueCoding = $loinc#LA31638-2 "Independent (including buttons, zips, laces, etc.)"
* item[+].linkId = "/96759-6"
* item[=].text = "Bowel control ability"
* item[=].answer.valueCoding = $loinc#LA31625-9 "Continent"
* item[+].linkId = "/96760-4"
* item[=].text = "Bladder control ability"
* item[=].answer.valueCoding = $loinc#LA31625-9 "Continent"
* item[+].linkId = "/96761-2"
* item[=].text = "Total score Barthel Index"
* item[=].answer.valueInteger = 100

Instance: non-smoker-example-1
InstanceOf: Observation
Usage: #example
Title: "non-smoker-example"
Description: "Example of patient smoking status"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus|6.1.0"
* status = #final
* category = $observation-category#social-history "Social History"
* category.text = "Social History"
* code = $loinc#72166-2 "Tobacco smoking status"
* code.text = "Tobacco smoking status"
* subject = Reference(bh-patient-example) "James Wolff"
* effectiveDateTime = "2024-02-01T16:27:04Z"
* performer = Reference(pcp-provider-example-1) "Dr. Doc Family"
* valueCodeableConcept = $sct#8392000 "Non-smoker (finding)"

Instance: substance-abuse-condition-example-1
InstanceOf: Condition
Usage: #example
Title: "substance-abuse-example"
Description: "Example of patient history of substance use"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns|6.1.0"
* clinicalStatus = $condition-clinical#active "Active"
* verificationStatus.coding.version = "4.0.0"
* verificationStatus.coding = $condition-ver-status#confirmed "Confirmed"
* verificationStatus.text = "Confirmed"
* category = $condition-category_1#health-concern "Health Concern"
* category.text = "Health Concern"
* code = $sct#371422002 "History of substance abuse (situation)"
* code.text = "History of Substance Abuse"
* subject = Reference(bh-patient-example) "James Wolff"
* onsetDateTime = "2007-12-14"
* recordedDate = "2007-12-14T15:15:07+00:00"

Instance: C-SSRS-example-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "Columbia-Suicide Severity Rating Scale (C-SSRS)"
Description: "Example of suicide risk assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "https://www.cms.gov/files/document/cssrs-screen-version-instrument.pdf"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/93246-7"
* item[=].text = "Have you wished you were dead or wished you could go to sleep and not wake up?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93247-5"
* item[=].text = "Have you actually had any thoughts of killing yourself?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93248-3"
* item[=].text = "Have you been thinking about how you might do this?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93249-1"
* item[=].text = "Have you had these thoughts and had some intention of acting on them?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93250-9"
* item[=].text = "Have you started to work out or worked out the details of how to kill yourself? Do you intend to carry out this plan?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93267-3"
* item[=].text = "Have you ever done anything, started to do anything, or prepared to do anything to end your life?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93269-9"
* item[=].text = "Was this within the past 3 months?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/93374-7"
* item[=].text = "Suicide risk level"
* item[=].answer.valueCoding = $loinc#LA9194-7 "Low"

Instance: hark-example-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "Humiliation, Afraid, Rape, and Kick questionnaire (HARK)"
Description: "Example of interpersonal violence assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "https://www.etsu.edu/institute/child-family-health/documents/mahf_dv_hark_c.pdf"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/76499-3"
* item[=].text = "Within the last year, have you been humiliated or emotionally abused in other ways by your partner or ex-partner?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/76501-6"
* item[=].text = "Within the last year, have you been afraid of your partner or ex-partner?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/76502-4"
* item[=].text = "Within the last year, have you been raped or forced to have any kind of sexual activity by your partner or ex-partner?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/76503-2"
* item[=].text = "Within the last year, have you been kicked, hit, slapped, or otherwise physically hurt by your partner or ex-partner?"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/76504-0"
* item[=].text = "Total score [HARK]"
* item[=].answer.valueInteger = 0

Instance: ace-example-1
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "Adverse Childhood Experiences (ACEs) Assessment"
Description: "Example of a mental trauma or PTSD assessment/screening"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-questionnaireresponse|6.1.0"
* questionnaire = "https://www.acesaware.org/wp-content/uploads/2022/07/ACE-Questionnaire-for-Adults-Identified-English-rev.7.26.22.pdf"
* status = #completed
* subject = Reference(bh-patient-example) "James Wolff"
* authored = "2024-02-01T20:50:32.718Z"
* author = Reference(ed-physician-example-1)
* item[0].linkId = "/82814-5"
* item[=].text = "Emotional abuse--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA33-6 "Yes"
* item[+].linkId = "/82815-2"
* item[=].text = "Physical abuse--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA33-6 "Yes"
* item[+].linkId = "/82816-0"
* item[=].text = "Sexual abuse--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA33-6 "Yes"
* item[+].linkId = "/82817-8"
* item[=].text = "Emotional neglect--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA33-6 "Yes"
* item[+].linkId = "/82818-6"
* item[=].text = "Physical neglect--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA33-6 "Yes"
* item[+].linkId = "/82820-2"
* item[=].text = "Domestic violence--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/82822-8"
* item[=].text = "Mental illness in household--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"
* item[+].linkId = "/82823-6"
* item[=].text = "Criminal household member--before 18 years old [ACE]"
* item[=].answer.valueCoding = $loinc#LA32-8 "No"

Instance: pregnancy-status-example-1
InstanceOf: Observation
Usage: #example
Title: "pregnancy-example"
Description: "Example of patient pregnancy status"
* meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-pregnancystatus|6.1.0"
* status = #final
* category = $observation-category#social-history "Social History"
* category.text = "Social History"
* code = $loinc#82810-3 "Pregnancy status"
* code.text = "Pregnancy Status"
* subject = Reference(bh-patient-example) "James Wolff"
* effectiveDateTime = "2024-02-01T10:39:52Z"
* performer = Reference(pcp-provider-example-1) "Dr. Doc Family"
* valueCodeableConcept.coding.version = "http://snomed.info/sct/731000124108"
* valueCodeableConcept.coding = $sct#60001007 "Not pregnant (finding)"
* valueCodeableConcept.text = "Not pregnant"
